version: '3'
services:
  db:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - 5432:5432
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
