#!/usr/bin/env bash

set -eu
set -o pipefail

cd $(dirname $0)/..

APIS_DIR=./apis
GOOGLEAPIS_DIR=./apis/vendor/googleapis
PROTO_GRAPHQL_DIR=./apis/vendor/proto-graphql
GRPC_GATEWAY_DIR=./apis/vendor/grpc-gateway

NEXUS_OUT_DIR=./gateway/__generated__/schema/types
APIS_OUT_DIR=./packages/apis/lib

mkdir -p $NEXUS_OUT_DIR
mkdir -p $APIS_OUT_DIR

./script/protocw --version

genPbNexus() {
  ./script/protocw \
    -I $GOOGLEAPIS_DIR \
    -I $GRPC_GATEWAY_DIR \
    -I $PROTO_GRAPHQL_DIR \
    -I $APIS_DIR \
    --plugin=protoc-gen-nexus=./node_modules/.bin/protoc-gen-nexus \
    --nexus_out=$NEXUS_OUT_DIR \
    --nexus_opt=import_prefix=@blankhat/apis/lib,partial_inputs,custom_type=google.type.Date=Date \
    "$@"
}

genPbJS() {
  ./script/protocw \
    -I $GOOGLEAPIS_DIR \
    -I $GRPC_GATEWAY_DIR \
    -I $PROTO_GRAPHQL_DIR \
    -I $APIS_DIR \
    --plugin=protoc-gen-grpc=./node_modules/.bin/grpc_tools_node_protoc_plugin \
    --plugin=./tmp/protobuf-javascript-3.21.2/bin/protoc-gen-js \
    --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
    --js_out=import_style=commonjs,binary:$APIS_OUT_DIR \
    --grpc_out=$APIS_OUT_DIR \
    --ts_out=$APIS_OUT_DIR \
    "$@"
}

targetProtos=(
  $APIS_DIR/blankhat/helloworld/*.proto
)

targetProtosWithoutNexus=(
  $GOOGLEAPIS_DIR/google/api/*.proto
  $GOOGLEAPIS_DIR/google/rpc/*.proto
  $GOOGLEAPIS_DIR/google/type/*.proto
  $GRPC_GATEWAY_DIR/protoc-gen-openapiv2/options/*.proto
  $PROTO_GRAPHQL_DIR/proto/graphql/*.proto
)

genPbJS ${targetProtos[@]} ${targetProtosWithoutNexus[@]} &
genPbNexus ${targetProtos[@]} &

wait
